### ISSUE TITLE
Support MSI Modern 14 B10MW

### ISSUE THREAD

**Issue by SteelT1** [BeardOverflow/msi-ec#100]
### Laptop model

Modern 14 B10MW

### EC firmware version

14D1EMS1.103

### EC memory dump

```
     | _0 _1 _2 _3 _4 _5 _6 _7 _8 _9 _a _b _c _d _e _f
-----+------------------------------------------------
0x0_ | 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x1_ | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x2_ | 00 00 00 00 00 00 00 00 00 00 00 80 e0 06 0b 0a
0x3_ | 02 05 00 05 50 0a 05 00 f4 0c 88 2c 4b 01 c0 00
0x4_ | 16 0d 39 00 46 08 75 fb a5 04 71 2b d0 0b fa 32
0x5_ | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x6_ | 00 00 00 00 00 00 00 00 2c 00 38 3e 44 4a 50 5a
0x7_ | 64 00 00 32 41 49 50 5a 64 50 04 03 03 03 03 03
0x8_ | 00 00 35 3a 3f 44 50 5a 64 00 00 32 41 49 50 5a
0x9_ | 64 4b 03 03 03 03 05 05 06 0f 78 06 0f 78 00 00
0xa_ | 31 34 44 31 45 4d 53 31 2e 31 30 33 30 36 31 39
0xb_ | 32 30 32 30 30 38 3a 30 39 3a 31 34 46 08 00 00
0xc_ | 00 01 25 00 00 9e 40 00 00 01 00 00 00 00 00 00
0xd_ | 00 00 00 00 70 00 00 00 24 44 3a 80 00 17 0c 1c
0xe_ | e2 02 00 00 10 00 00 00 00 00 00 00 00 84 00 80
0xf_ | 00 00 80 83 0d 00 05 00 00 00 00 00 00 00 00 00
```

### GPU

iGPU only (Intel)

### Is your keyboard RGB?

No (single color)

**Comment by SteelT1** [comment]
Finally got around to setting up a bootable Windows install using Ventoy's VHD boot feature, and here's what I found so far, values gathered from RWEverything.

## Notes
| Name  | Address | Values Seen | Extra Notes |
| ------------- | ------------- |  ------------- | ------------- |
| Webcam  | 0x2E  |  off = 0x09, on = 0x0B  | N/A |
| Webcam  block | 0x2F  |  off = 0x0A, on = 0x0C  | N/A |
| Fn/Win key swap | 0xBF  |  left = 0x00, right = 0x10  | N/A |
| Battery Mode  | 0xEF  | max = 0xE4, medium = 0xD0, min = 0xBC | N/A |
| Cooler Boost  | 0x98  | off = 0x06, on = 0x86 | MSI Creator Center has no dedicated setting for cooler boost and instead ties it to the fan speed setting, with auto being set to value 06 in the EC|
| Keyboard Backlight | 0xF3  | full = 0x83, half = 0x82, on = 0x81, off = 80 | N/A |
| Speaker mute led state | 0x2C  |  off = 0xE0, on = 0xE4 | N/A |
| Mic mute led state | 0x2B  |  off = 0x88, on = 0x8C | N/A |

## Sensors
```
CPU temperature address: 0x68
Battery charge address: 0x42
```

## Not certain
* Super Battery
* Fan Modes

**Comment by glpnk** [comment]
F3 is keyboard brightness, and for some reasons MSI power off keyboard backlight on it

**Comment by glpnk** [comment]
Can you additionaly check high performance mode. When you select it, gear or similar icon might appear, so I'm inerested in fan curve mode

**Comment by SteelT1** [comment]
Options available for fan speed

![image](https://github.com/BeardOverflow/msi-ec/assets/9903201/fb5347a4-242c-428a-a6e3-d8f674317e20)

This also has seem to have fan curve settings for GPU even though it's an iGPU.
![image](https://github.com/BeardOverflow/msi-ec/assets/9903201/9a80c477-59c3-411e-a4b1-37952f05e8ca)
![image](https://github.com/BeardOverflow/msi-ec/assets/9903201/e291bd90-5031-42b4-a486-a9180ee2d561)

**Comment by glpnk** [comment]
I have only igpu too and have 2 menu. But on latest update of MSI Center (not Center pro) they hide GPU menu

**Comment by SteelT1** [comment]
Made a mistake in the earlier comment listing the modes, and `F4` for silent was supposed to be `10`

**Comment by glpnk** [comment]
Please check output of F4 on fancurve mode

**Comment by glpnk** [comment]
Also, please check address 0xD5 after changing user scenario in app

**Comment by SteelT1** [comment]
F4 is set to 80 when set to fan curve mode is set to advanced, otherwise is set to 00 when fan mode is to auto, and cooler boost seems to retain the value, so switching from advanced to cooler boost will leave F4 set to 80.

Changing user scenario in app doesn't seem to set D5, it's always at 00 no matter what mode.

**Comment by glpnk** [comment]
Thank you, that's all I need

**Comment by glpnk** [comment]
@SteelT1 ready

**Comment by teackot** [comment]
Merged in #140

**Comment by glpnk** [comment]
@SteelT1 Hi, please update AUR package

**Comment by SteelT1** [comment]
> [@SteelT1](https://github.com/SteelT1) Hi, please update AUR package

should be up to date

**Comment by glpnk** [comment]
@SteelT1 Thanks, does aur allows to add co maintainer with write permissions?

**Comment by SteelT1** [comment]
@glpnk yeah, additional users can be added as a co-maintainer

**Comment by glpnk** [comment]
Can you add me? `glpnk@proton.me`

**Comment by SteelT1** [comment]
Done, you should be able to push to it now

**Comment by glpnk** [comment]
thanks, got access
