### ISSUE TITLE
MSI GF63 Thin 9sc make error!

### ISSUE THREAD

**Issue by yuan-0816** [BeardOverflow/msi-ec#104]
### Laptop model

GF63 Thin 9sc

### Description

run ```make```

```
make[1]: Entering directory '/usr/src/linux-headers-6.2.0-37-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  You are using:           gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
make[1]: Leaving directory '/usr/src/linux-headers-6.2.0-37-generic'
```

run ```sudo make install```

```
mkdir -p /lib/modules/6.2.0-37-generic/extra
cp msi-ec.ko /lib/modules/6.2.0-37-generic/extra
depmod -a
echo msi-ec > /etc/modules-load.d/msi-ec.conf
modprobe -v msi-ec
insmod /lib/modules/6.2.0-37-generic/extra/msi-ec.ko 
modprobe: ERROR: could not insert 'msi_ec': Key was rejected by service
make: *** [Makefile:38: install] Error 1
```

**Comment by glpnk** [comment]
Did your kernel come with preinstalled `msi-ec` module? Check
```bash
modinfo msi-ec
```
If it shows signed module than it probably come with kernel.

In this case run
```bash
sudo make dkms-install
```

**Comment by glpnk** [comment]
Actually looks like your hardware is not supported. You can use template named `New firmware request` to share required info.

**Comment by teackot** [comment]
There are 3 problems actually:

1. Like @glpnk said, you need to install the DKMS version
2. The error you get ("Key was rejected by service") may be related to secure boot. Do you have it enabled?
3. Yes, it is most likely not supported:  the version is `16R3EMS1.104` on the official MSI support page

**Comment by teackot** [comment]
> you need to install the DKMS version

Side note: we should add this to readme, right now it tells you to use `make install`

**Comment by yuan-0816** [comment]
> Did your kernel come with preinstalled `msi-ec` module? Check
> 
> ```shell
> modinfo msi-ec
> ```
> 
> If it shows signed module than it probably come with kernel.
> 
> In this case run
> 
> ```shell
> sudo make dkms-install
> ```

I run ```modinfo msi-ec```
and have this 
```
ubuntu:~$ modinfo msi-ec
filename:       /lib/modules/6.2.0-37-generic/extra/msi-ec.ko
version:        0.08
description:    MSI Embedded Controller
author:         Nikita Kravets <teackot@gmail.com>
author:         Aakash Singh <mail@singhaakash.dev>
author:         Jose Angel Pastrana <japp0005@red.ujaen.es>
license:        GPL
srcversion:     42DC840AF3304DA246EA09C
depends:        
retpoline:      Y
name:           msi_ec
vermagic:       6.2.0-37-generic SMP preempt mod_unload modversions 
parm:           firmware:Load a configuration for a specified firmware version (charp)
parm:           debug:Load the driver in the debug mode, exporting the debug attributes (bool)

```
