### ISSUE TITLE
msi-ec not start

### ISSUE THREAD

**Issue by SPRATAY** [BeardOverflow/msi-ec#179]
### Laptop model

msi alpha 15 b5eek

### EC firmware version

cat: /sys/devices/platform/msi-ec/fw_version: Нет такого файла или каталога

### Description

i installed msi-ec no dkms
❯ sudo dmesg | grep msi
[   17.471314] ACPI: battery: new extension: msi-ec
❯ sudo ls /sys/devices/platform/
ACPI0011:00  AMDI0010:03  MSFT0101:00  PNP0C0C:00  PNP0C14:01	efivars.0  intel_rapl_msr.0  pcspkr  reg-dummy     rtc-efi.0	snd-soc-dummy  uevent
AMDI0005:00  AMDI0030:00  PNP0103:00   PNP0C0E:00  acpi-cpufreq  i8042	   microcode	     power   regulatory.0  serial8250	sp5100-tco

why problem

**Comment by glpnk** [comment]
You need to remove in-kernel msi-ec version first, then install git version. DKMS do it all automatically

**Comment by SPRATAY** [comment]
> You need to remove in-kernel msi-ec version first, then install git version. DKMS do it all automatically

wait, i dont understand how to remove from the kernel, about dkms there may be problems I use Gentoo openrc(I already tried it did not work)

**Comment by glpnk** [comment]
Then you can recompile kernel without msi-ec and install it

**Comment by SPRATAY** [comment]
> Then you can recompile kernel without msi-ec and install it

ok i rebuild kernel
and i git pull msi-ec
```
❯ make
make[1]: вход в каталог «/usr/src/linux-6.6.62-xanmod1-dist»
Makefile:2227: !!!! WARNING !!!!
Makefile:2228: This kernel was configured and installed by the package manager.
Makefile:2229: "make" should not be run manually here.
Makefile:2230: See also: https://wiki.gentoo.org/wiki/Project:Distribution_Kernel
Makefile:2231: See also: https://wiki.gentoo.org/wiki/Kernel/Configuration
Makefile:2232: !!!! WARNING !!!!
/usr/src/linux-6.6.62-xanmod1-dist/Makefile:2227: !!!! WARNING !!!!
/usr/src/linux-6.6.62-xanmod1-dist/Makefile:2228: This kernel was configured and installed by the package manager.
/usr/src/linux-6.6.62-xanmod1-dist/Makefile:2229: "make" should not be run manually here.
/usr/src/linux-6.6.62-xanmod1-dist/Makefile:2230: See also: https://wiki.gentoo.org/wiki/Project:Distribution_Kernel
/usr/src/linux-6.6.62-xanmod1-dist/Makefile:2231: See also: https://wiki.gentoo.org/wiki/Kernel/Configuration
/usr/src/linux-6.6.62-xanmod1-dist/Makefile:2232: !!!! WARNING !!!!
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-pc-linux-gnu-gcc (Gentoo 14.2.1_p20241116 p3) 14.2.1 20241116
  You are using:           gcc (Gentoo 14.2.1_p20241116 p3) 14.2.1 20241116
  CC [M]  /home/spratay/git/hub/msi-ec/msi-ec.o
  MODPOST /home/spratay/git/hub/msi-ec/Module.symvers
  CC [M]  /home/spratay/git/hub/msi-ec/msi-ec.mod.o
  LD [M]  /home/spratay/git/hub/msi-ec/msi-ec.ko
make[1]: выход из каталога «/usr/src/linux-6.6.62-xanmod1-dist»

sudo make install
Пароль: 
mkdir -p /lib/modules/6.6.62-xanmod1-dist/extra
cp msi-ec.ko /lib/modules/6.6.62-xanmod1-dist/extra
depmod -a
echo msi-ec > /etc/modules-load.d/msi-ec.conf
modprobe -v msi-ec

ls /sys/devices/platform/
ACPI0011:00  AMDI0010:03  MSFT0101:00  PNP0C0C:00  PNP0C14:01	efivars.0  intel_rapl_msr.0  pcspkr  reg-dummy     rtc-efi.0	snd-soc-dummy  uevent
AMDI0005:00  AMDI0030:00  PNP0103:00   PNP0C0E:00  acpi-cpufreq  i8042	   microcode	     power   regulatory.0  serial8250	sp5100-tco
```
why?

**Comment by glpnk** [comment]
Module not loads automatically, reboot after installation.

I see that is not Gentoo way of installing modules, would be nice if you'll find how to do it properly

**Comment by SPRATAY** [comment]
> Module not loads automatically, reboot after installation.
> 
> I see that is not Gentoo way of installing modules, would be nice if you'll find how to do it properly

I understood that the kernel already comes with such a module, so I couldn’t understand why it doesn’t start, I’ll have to look for a way to replace it with this one

**Comment by glpnk** [comment]
Module included to kernel have only battery charge limit and not all models from this repo

**Comment by SPRATAY** [comment]
> Module included to kernel have only battery charge limit and not all models from this repo

I've already figured this out, now I need to figure out how to replace the module that works now with this one

simply removing it doesn't help, nor does replacing it

**Comment by SPRATAY** [comment]
if you manually delete and sign it then it starts working thank you for opening my eyes to what was the matter, all that remains is to find a solution how to disable the one that comes with the kernel and use this one

**Comment by glpnk** [comment]
If you build kernel yourself - find how to blacklist module from building

**Comment by SPRATAY** [comment]
> If you build kernel yourself - find how to blacklist module from building

Well, my kernel is built using dracut, I excluded it from the build but for some reason it still builds, the easiest way is to add it to the blacklist in modprobe, but the problem is that you need to explicitly point to the module from Git in its directory

```
❯ sudo modprobe -r msi_ec
Пароль: 
❯ sudo insmod /lib/modules/6.6.62-xanmod1-dist/extra/msi-ec.ko
```

Of course, you can try to simply change msi-ec to msi-ec-git, but the problem is that modprobe can first load ms-ec-git, which leads to an error, and then unload msi-ec itself, it’s a pity that they cannot work separately from each other friend

**Comment by glpnk** [comment]
Dracut is a tool for creating initramfs (boot image), not for building kernel from sources. You can probably unset `msi-ec` in `make menuconfig` of kernel sources, or manually replace sources of `msi-ec` in kernel

**Comment by SPRATAY** [comment]
> Dracut is a tool for creating initramfs (boot image), not for building kernel from sources. You can probably unset `msi-ec` in `make menuconfig` of kernel sources, or manually replace sources of `msi-ec` in kernel

I did just that, disable this module in the config, there are simply no words, I’m tired

**Comment by glpnk** [comment]
Okay, I understand yoo. But why you you use gentoo? If not as challenge?

**Comment by SPRATAY** [comment]
> Okay, I understand yoo. But why you you use gentoo? If not as challenge?

In short, all Linux distributions are shit, this shit at least obeys my will

**Comment by glpnk** [comment]
Okay, how you install kernel? With emerge or manually

**Comment by glpnk** [comment]
Do you use `sys-kernel/xanmod-kernel` or `sys-kernel/xanmod-sources`?

**Comment by glpnk** [comment]
Okay. I mean, if you use binary kernel, you can't force it to not compile modules. But you can manually remove built-in module for current kernel version, which probably will be returned on update. Other way is creating script, which will load a module on startup.

Let's see where modules are located to remove built-in
```
find / -name "msi-ec.ko*" 2>/dev/null
```

**Comment by SPRATAY** [comment]
> Okay. I mean, if you use binary kernel, you can't force it to not compile modules. But you can manually remove built-in module for current kernel version, which probably will be returned on update. Other way is creating script, which will load a module on startup.
> 
> Let's see where modules are located to remove built-in
> 
> ```
> find / -name "msi-ec.ko*" 2>/dev/null
> ```

```
/home/spratay/git/hub/msi-ec/msi-ec.ko
/usr/lib/modules/6.6.61-xanmod1-dist/kernel/drivers/platform/x86/msi-ec.ko
/usr/lib/modules/6.6.62-xanmod1-dist/extra/msi-ec.ko
```
I understand this, you just need to understand how to make Modprobe load MSI-EC from the catalog

/usr/lib/modules/6.6.62-xanmod1-dist/extra/msi-ec.ko

**Comment by glpnk** [comment]
Kernel prioritize loading from `/kernel/` than from `/extra/`, so simplest by my opinion is just to remove the next file
```
/usr/lib/modules/6.6.61-xanmod1-dist/kernel/drivers/platform/x86/msi-ec.ko
```

**Comment by glpnk** [comment]
I know this because once or twice dkms messed up and keep both versions due to kernel update with same version

**Comment by SPRATAY** [comment]
> The kernel prioritizes loading from `/kernel/` over `/extra/`, so the easiest thing to do, in my opinion, is to just remove the next file:

I have completely disabled the module in the kernel,but I can only load the downloaded module this way, through modprobe I don’t know how to write it

```
sudo insmod /lib/modules/6.6.62-xanmod1-dist/extra/msi-ec.ko
```

**Comment by glpnk** [comment]
You should to remove module from blacklist to allow auto loading, or you can run insmod on startup

Anyway, it's wrong way for gentoo

**Comment by SPRATAY** [comment]
> You should to remove module from blacklist to allow auto loading, or you can run insmod on startup
> 
> Anyway, it's wrong way for gentoo

I seem to have solved this problem, thanks for the help,

I just need to understand why my battery now consumes more after turning off the power

and why the ice for sound and microphone does not light up after pressing, most likely this is a pipewire problem

**Comment by mutchiko** [comment]
>I just need to understand why my battery now consumes more after turning off the power

@SPRATAY look at the power button and tell me what color is it right now?

 >most likely this is a pipewire problem

it is, we are trying to find a way to trigger LEDs by pipewire events, if you find a solution please share it with us.

**Comment by glpnk** [comment]
> I just need to understand why my battery now consumes more after turning off the power

MSI have problems with optimization

> why the ice for sound and microphone does not light up after pressing, most likely this is a pipewire problem

check

```
ls /sys/devices/platform/msi-ec/leds/
```

If all LEDs are present, LED triggers might not exist. Mute events are generated by Alsa

**Comment by SPRATAY** [comment]
> >I just need to understand why my battery now consumes more after turning off the power
> 
> @SPRATAY look at the power button and tell me what color is it right now?
> 
>  >most likely this is a pipewire problem
> 
> it is, we are trying to find a way to trigger LEDs by pipewire events, if you find a solution please share it with us.

Emm red

no wait before i installed msi-ec i had 12w consumption and now i have 40w consumption maybe i have tlp issues but i doubt

**Comment by mutchiko** [comment]
@SPRATAY  >red

your dGPU is on, thats why you don't get 10 hours battery. restart should fix it.

>maybe i have tlp issues

tlp wakes up dGPU for no reson, use power profiles daemon, its better.

keep an eye out for the power button color, red means dGPUis on, white means its off (you get way better battery life).

**Comment by mutchiko** [comment]
>write sensors the lights up red, shows the temperature, and then white again,

@SPRATAY dGPU needs to wake up if you want to read sensors, and basically any action related to the video card (usage/power monitoring for ex) will wake it up and drain extra power.

>I'm going crazy now

please close this issue before you do that, thanks.

**Comment by SPRATAY** [comment]
> ls /sys/devices/platform/msi-ec/leds/

```
ls /sys/devices/platform/msi-ec/leds/
platform::micmute  platform::mute

❯ cat /sys/devices/platform/msi-ec/leds/platform::micmute/trigger
none usb-gadget usb-host rfkill-any rfkill-none kbd-scrolllock kbd-numlock kbd-capslock kbd-kanalock kbd-shiftlock kbd-altgrlock kbd-ctrllock kbd-altlock kbd-shiftllock kbd-shiftrlock kbd-ctrlllock kbd-ctrlrlock ADP1-online disk-activity disk-read disk-write mtd nand-disk cpu cpu0 cpu1 cpu2 cpu3 cpu4 cpu5 cpu6 cpu7 panic BAT1-charging-or-full BAT1-charging BAT1-full BAT1-charging-blink-full-solid rc-feedback audio-mute [audio-micmute] bluetooth-power hci0-power rfkill0 phy0rx phy0tx phy0assoc phy0radio rfkill1 r8169-0-500:00:link r8169-0-500:00:1Gbps r8169-0-500:00:100Mbps r8169-0-500:00:10Mbps
❯ cat /sys/devices/platform/msi-ec/leds/platform::mute/trigger
none usb-gadget usb-host rfkill-any rfkill-none kbd-scrolllock kbd-numlock kbd-capslock kbd-kanalock kbd-shiftlock kbd-altgrlock kbd-ctrllock kbd-altlock kbd-shiftllock kbd-shiftrlock kbd-ctrlllock kbd-ctrlrlock ADP1-online disk-activity disk-read disk-write mtd nand-disk cpu cpu0 cpu1 cpu2 cpu3 cpu4 cpu5 cpu6 cpu7 panic BAT1-charging-or-full BAT1-charging BAT1-full BAT1-charging-blink-full-solid rc-feedback [audio-mute] audio-micmute bluetooth-power hci0-power rfkill0 phy0rx phy0tx phy0assoc phy0radio rfkill1 r8169-0-500:00:link r8169-0-500:00:1Gbps r8169-0-500:00:100Mbps r8169-0-500:00:10Mbps
```

My LEDs light up if I manually change the value from 0 to 1

and yes, now the LED only works for the microphone, and then if I turn it off for the speaker in the webcam, but this does not apply, for example, to bluetooth headphones and so on

**Comment by glpnk** [comment]
Not sure, how main sound card should announce itself to system as main, but on some devices mute led works out of box.

ALSA drivers send triggers to LED kernel subsystem, which toggle them. Not sure if similar exists for PulseAudio or PipeWire.

Bluetooth audio not use ALSA, and works in userspace, so it's not accessible for triggers. I've tried to find a way to find the correct path to main soundcard in sysfs, but failed, so playing with soundcard number in this guide https://github.com/BeardOverflow/msi-ec/discussions/130#discussioncomment-11010018 seems like only option for me.

**Comment by SPRATAY** [comment]
> Not sure, how main sound card should announce itself to system as main, but on some devices mute led works out of box.
> 
> ALSA drivers send triggers to LED kernel subsystem, which toggle them. Not sure if similar exists for PulseAudio or PipeWire.
> 
> Bluetooth audio not use ALSA, and works in userspace, so it's not accessible for triggers. I've tried to find a way to find the correct path to main soundcard in sysfs, but failed, so playing with soundcard number in this guide [#130 (comment)](https://github.com/BeardOverflow/msi-ec/discussions/130#discussioncomment-11010018) seems like only option for me.

really worked thx i love you

**Comment by glpnk** [comment]
this thing not persist after reboot

**Comment by SPRATAY** [comment]
> this thing not persist after reboot

;(
