### ISSUE TITLE
Help porting on MSI Bravo 17 A4DDR

### ISSUE THREAD

**Issue by EricV** [BeardOverflow/msi-ec#20]
With the general announcement, I was hoping to be able to manage the battery mode. Reading the doc and the code I realize it only works with a given PC and a given ec firmware version.

Can we have a kind of porting manual?

**Comment by teackot** [comment]
> Reading the doc and the code I realize it only works with a given PC and a given ec firmware version

Yeah, all firmware versions have different configurations. I hope it will at least be narrowed down to the major version when we get some more feedback.

> Can we have a kind of porting manual?

I am working on a debug mode right now, see the draft PR. I will add a manual to readme when the mode is finished.

Right now debug mode is available in my fork. Follow [these](https://github.com/BeardOverflow/msi-ec/issues/18#issuecomment-1435733090) steps to get an EC memory dump and attach it here so I can take a look.

If you have windows, you can also try [this app](https://github.com/ThePBone/MsiEcRamEditor) and play around with settings in the official MSI app to see how they reflect on the EC memory.

**Comment by teackot** [comment]
Oh, and also, please tell me your EC firmware version. (`cat /sys/devices/platform/msi-ec/fw_version` with the driver loaded)

**Comment by EricV** [comment]
On 18/02/2023 23:24, teackot wrote:
> I am working on a debug mode right now, see the draft PR. I will add a 
> manual to readme when the mode is finished.

I found your fork reading the bug reports and pull requests

> If you have windows, you can also try this app 
> <https://github.com/ThePBone/MsiEcRamEditor> and play around with 
> settings in the official MSI app to see how they reflect on the EC memory.

I have windows and the MSI crap that I use only for battery/power 
management and bios and ec firmware version. But at least I can try this 
app.

Thanks for getting the time to answer, I will try your fork in debug 
mode but need some time as I must add signature also.

**Comment by EricV** [comment]
On 19/02/2023 12:07, Eric Valette wrote:
> On 18/02/2023 23:24, teackot wrote:
>> I am working on a debug mode right now, see the draft PR. I will add a 
>> manual to readme when the mode is finished.
> 
> I found your fork reading the bug reports and pull requests
> 
>> If you have windows, you can also try this app 
>> <https://github.com/ThePBone/MsiEcRamEditor> and play around with 
>> settings in the official MSI app to see how they reflect on the EC 
>> memory.
> 
> I have windows and the MSI crap that I use only for battery/power 
> management and bios and ec firmware version. But at least I can try this 
> app.

Unfortunately the tool returns only 0. The MSI dragon app list the 
firmware version

BIOS Version:                 E17FKAMS.117
BIOS Release Date:            2020/10/29
EC Version:                  17FKEMS1.10A0916202013:55:22

May be a different beast of EC memory?

-- eric

**Comment by teackot** [comment]
I also found [this](https://www.reddit.com/r/MSILaptops/comments/jf0bwx/adjusting_battery_charge_level_without_dragon/) reddit post suggesting RWEverything, maybe it will work?

**Comment by EricV** [comment]
On 2/19/2023 12:59 PM, teackot wrote:
>
> I also found this 
> <https://www.reddit.com/r/MSILaptops/comments/jf0bwx/adjusting_battery_charge_level_without_dragon/> 
> reddit post suggesting RWEverything, maybe it will work?
>

This one did work : I think you can see the EC version I already put in 
previous mail.

**Comment by teackot** [comment]
- battery thresholds - [0xef]
- webcam - ?
- fn / win - [0xbf ?]
- cooler boost - [0x98]
- shift mode - [0xf2], available modes: ?
- super battery - ? (may be unsupported)
- fan mode - [0xf4], available modes: ?
- cpu temp - [0x68]
- realtime fan speed - [0x71] or [0xc9]
- basic mode fan speed - [0x89] (if available)
- mute and micmute LEDs - (0x2b, 0x2c) or (0x2c, 0x2d); On/off values - ?
- backlight - [0xf3]; functional - ?

Can you please toggle your mute and micmute LEDs and switch the Fn/Win keys and tell me what happens

Also, swicth between different power profiles and tell me how the [0xf2] changes, and maybe other addresses too (I am particularly intrested in additional addresses set by super battery mode, apart from 0xf2 f3 and f4)

And one more question - does your laptop support setting constant fan speed (basic fan mode)

**Comment by EricV** [comment]
For                                            0xF2   0xF3     0xF4    0xD5
Extreme Perf                             C4      82         00       A1
Balanced                                   C1      82         00       A2
Silent                                         C1      82         10       A2
Super Battery                            C2      80         80       A5

F3 is indeed the keyboard backlight: if I use the keyboard it can go form 80 to (no light) to 83.  Note that F4 may chnages the last byte was D once but the first one did change to 1 for Silent.

Regarding 0xef: for the battery:

50->60 % (best for battery) BC
70->80 % (balanced) D0
100% (full charge) E4

Webcam is indeed 2E: No Cam 49 /Cam enabled 4B
Mute is 2C: Muted is 36 Unmuted is 32

Did not found volume up or down.

**Comment by teackot** [comment]
> ...0xD5
> ...A1
> ...A2
> ...A2
> ...A5

That's interesting. It seems to have a set of mode values... Judging by some Reddit threads and other configurations, I wonder if this address is related to the GPU

Basic fan mode is unsupported

> F3 is indeed the keyboard backlight: if I use the keyboard it can go form 80 to (no light) to 83. Note that F4 may chnages the last byte was D once but the first one did change to 1 for Silent.
> 
> 50->60 % (best for battery) BC
> 70->80 % (balanced) D0
> 100% (full charge) E4
> 
> Webcam is indeed 2E: No Cam 49 /Cam enabled 4B
> Mute is 2C: Muted is 36 Unmuted is 32

Got it

**Comment by teackot** [comment]
Okay, I added a config for your laptop. You can find it on the new_configs branch of my repo.

Didn't add different 0xD5 modes yet as it requires to change how we store them in configs.

Can you please test it for me, particularly webcam_block ("on" - webcam is off and blocked, "off" - webcam is unblocked), Fn/Win swap (write "left" or "right" into the fn_key attribute) and mute LED and kbd backlight in the leds/ subdirectory

**Comment by EricV** [comment]
Thanks a lot I tested it? Modules loads and seems functional.  Tested the battery mode OK. I'm a bit worried about testing the webcam as apparently I cannot modify it via keyboard afterwards and I have no mode  to do that on windows even in MSI dragon app.

Thanks a lot anyway.

**Comment by teackot** [comment]
When you tested the webcam address (0x2e), did you toggle your webcam with a keyboard key or from Dragon Center? If it was Dragon Center (or both), then yeah,  you don't have webcam_block function, and kbd key and dragon center switch do the same thing.

If you only tested the keyboard button, then Dragon Center switch may be the webcam_block, but if you're concerned - don't test it from Linux

**Comment by EricV** [comment]
I used th webcam button Fn from keyboard. I have nothing in dragon center apps. I do not have led mic either. Led is only for webcam.

Thanks again.

**Comment by teackot** [comment]
Oh, okay then, I'll remove it.

Thanks for helping the project grow!

I'll come back here when I add the 0xD5 thingy when I have time for it

**Comment by EricV** [comment]
In the various mode Extreme Perf, balanced ... I forgot to tell you have a user defined mode with two possible value drop down menu for performance (sure for this one) and fan (from memory I'm on Linux right now). I did not play yet with this user defined mode.

Tell me if you think it is worth. Have a nice day.

**Comment by teackot** [comment]
Merged! Thank you for your help!

> In the various mode Extreme Perf, balanced ... I forgot to tell you have a user defined mode with two possible value drop down menu for performance (sure for this one) and fan (from memory I'm on Linux right now). I did not play yet with this user defined mode.
> 
> Tell me if you think it is worth. Have a nice day.

Sorry, didn't see your message. I figured out what the custom modes are. There should be 4 modes, something like eco, balanced, high and extreme. The second drop-down is fan mode, we already know its values.

**Comment by teackot** [comment]
Closing since no more help is needed yet

Adding a label to remember to add super battery and backlight modes when they are implemented
