### ISSUE TITLE
GP66 Leopard 10UG (1542EMS1.102)

### ISSUE THREAD

**Issue by teackot** [BeardOverflow/msi-ec#23]
@vic1184

Creating a separate issue here (original - #18). First of all, TYSM for recording a video, it made it much easier to see the changes

Now here is what I figured out:

- battery thresholds - [0xef]
- webcam - [0x2e] bit1?
- monitor overdrive - [0x2e] bit4 ?
- Fn/Win swap - you didn't show it in the video
- cooler boost - standard [0x98] bit7
- shift mode - [0xf2], all modes are available
- super battery - [0xd5], mask = 0x0f (it may be the same for my laptop)
- fan mode - [0xf4], no basic mode
- realtime CPU temp - standard [0x68]
- realtime CPU fan speed - [0xc9]
- realtime GPU temp - [0x80]
- mute/micmute LEDs - you wasn't in the video

I'll try to find the crosshair address later.

**Comment by teackot** [comment]
Regarding the keyboard backlight - RGB backlight isn't controlled by EC. You can try OpenRGB, maybe it will work.

**Comment by vic1184** [comment]
Hello! Thank you too for spending time and skills on this - I'm glad to help!

https://www.youtube.com/watch?v=dNYPGdj8E9c

I made another video to show the Fn/Win swap button and the webcam button. Hope it can help. I also shown my laptop's keyboard, it doens't have any mic mute button. The speaker "mute" button on the right of the "up" key already works on Linux.

Regarding the keyboard, I'm now using msi-perkeyrgb on Linux Mint which works somewhat ok besides lacking a GUI and not perfectly supporting my keyboard. But will try OpenRGB, thanks for the reccomendation.

**Comment by teackot** [comment]
- Fn/Win - [0xbf] bit4. It is reversed, but I will fix it later
- webcam - [0x2e] bit1, camera block is unsupported

Great job! We found all parameters currently supported by the driver! It will be merged with other configs soon

**Comment by teackot** [comment]
Merged! Not closing the issue since I still want to find crosshair address and maybe implement monitor overdrive

**Comment by vic1184** [comment]
Thanks! It seems to be working well on my configuration, but I haven't tested the various shift modes yet.

**Comment by vic1184** [comment]
Hello. After a bit of testing I think I got it figured what works and what doesn't.
-the various shift mode work, howevever after reboot the entry in the shift_mode file switches back to "unspecified"
-GPU's realtime_fan_speed always reads 128 and realtime_temperature always reads 0.
-it already happened a couple of times that the msi-ec directory in /sys/devices/platform deleted by itself. I still have to figure out what caused it, maybe it was a kernel update but it seemed very odd to me.

**Comment by teackot** [comment]
Hi!

> the various shift mode work, howevever after reboot the entry in the shift_mode file switches back to "unspecified"

Firmware resets it to "unspecified" after poweroff and sleep, we can't fix it on the driver side. However, I'm in progress of making a userspace utility which will read a config file and write to EC through this driver, restoring your configured values on reboots and wakeups.

> GPU's realtime_fan_speed always reads 128 and realtime_temperature always reads 0

That's actually a bug, since realtime_fan_speed is marked as unsupported on your firmware. Looks like the driver doesn't disable unsupported cpu/ and gpu/ entries.

Regarding gpu's rt temperature - I'll mark it as unsupported.

> it already happened a couple of times that the msi-ec directory in /sys/devices/platform deleted by itself. I still have to figure out what caused it, maybe it was a kernel update but it seemed very odd to me.

Yes, that's odd. It may or may not be the driver problem. You should check the logs if this happens again.

Thanks for the feedback!

**Comment by vic1184** [comment]
Hello! I can confirm it's 100% the kernel update. I just updated to 5.15.0-72-generic (kernel only) and the msi-ec folder disappeared.

**Comment by teackot** [comment]
Closing until super battery (and possibly crosshair & monitor override) are supported
