### ISSUE TITLE
1552EMS1 duplicated

### ISSUE THREAD

**Issue by glpnk** [BeardOverflow/msi-ec#48]
check ```ALLOWED_FW_11``` and ```ALLOWED_FW_2```

In FW_2 version ```1552EMS1.118```
In FW_11 version ```1552EMS1.115```

Also I think that usage of one config for two+ models is bad idea for now

**Comment by serfreeman1337** [comment]
Also module refuses to load on Modern A11M with updated bios:
`msi_ec: Firmware version is not supported: '1552EMS1.120'`

**Comment by teackot** [comment]
The major version of the EC FW is the same. The only difference is the minor version (115 and 118), so they should probably have the same addresses. We can read the official MSI changelogs to see if they made any major changes

**Comment by teackot** [comment]
> We can read the official MSI changelogs to see if they made any major changes

Can't find them though

**Comment by teackot** [comment]
CONF2 was taken from @ThePBone's [msi-ec-modern](https://github.com/ThePBone/msi-ec-modern/) repo.

CONF11 was added by @LucaPatarca 

@LucaPatarca Can you please show us an EC dump from the debug mode? (`sudo make reload-debug` and then `cat /sys/devices/platform/msi-ec/debug/ec_dump`)

**Comment by glpnk** [comment]
Well, as #40 and [`msi-ec-modern`](https://github.com/ThePBone/msi-ec-modern/) fork

+ `1552EMS1` is WMI2 device, because intel 11 gen
+ fan mode address is `0xd4`, which is right
+ preset memory table mentions `0xd2` as shift, `0xd3` as keyboard, `0xd4` as fan

Only incorrect value in `conf_2` was shift mode addres, which should be `0xd2`

**Comment by cvlc12** [comment]
Hi,
I just noticed I still have this inconsistency on my Modern 15 A11M:
```
kernel: DMI: Micro-Star International Co., Ltd. Modern 15 A11M/MS-1552, BIOS E1552IMS.121 04/13/2022
kernel: msi_ec: Firmware version is not supported: '1552EMS1.120'
```
Using `6.15.8-arch1-1`

**Comment by glpnk** [comment]
You was wrong, also your device is supported

**Comment by cvlc12** [comment]
What do you mean?

**Comment by glpnk** [comment]
read #382 and try to fix your installation issues and never ever use `make install`
