### ISSUE TITLE
Add support for MSI Modern 15 B7M

### ISSUE THREAD

**Issue by CosmicRaptor** [BeardOverflow/msi-ec#89]
### Laptop model

Modern 15 B7M  

### EC firmware version

15HKEMS1.104

### GPU

iGPU only (AMD)

### Is your keyboard RGB?

No (single color)

### Additional context

I'm on windows and willing to do an EC dump if someone can guide me, I never did this before.

**Comment by CosmicRaptor** [comment]
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/4f3c4082-6cdd-43c8-a1c3-d9ff0745f2d6)
RWEverything does not seem to work.

**Comment by CosmicRaptor** [comment]
EC Dump as below

```Type:Embedded Controller: 0066,0062
Width:01
00=00 01=80 02=00 03=00 04=00 05=00 06=00 07=00 
08=00 09=00 0A=00 0B=00 0C=00 0D=00 0E=00 0F=00 
10=00 11=00 12=00 13=00 14=00 15=00 16=00 17=00 
18=00 19=00 1A=00 1B=00 1C=00 1D=00 1E=00 1F=00 
20=00 21=00 22=00 23=00 24=00 25=00 26=00 27=00 
28=00 29=00 2A=00 2B=80 2C=E0 2D=07 2E=09 2F=0B 
30=03 31=03 32=00 33=05 34=51 35=0A 36=05 37=00 
38=F4 39=0C 3A=88 3B=2C 3C=4B 3D=01 3E=80 3F=00 
40=16 41=0D 42=1A 43=00 44=49 45=0C 46=A2 47=08 
48=29 49=03 4A=4A 4B=2E 4C=05 4D=0C 4E=FA 4F=32 
50=00 51=00 52=00 53=00 54=00 55=00 56=00 57=00 
58=00 59=00 5A=00 5B=00 5C=00 5D=00 5E=00 5F=00 
60=00 61=00 62=00 63=00 64=00 65=00 66=00 67=00 
68=32 69=00 6A=36 6B=3A 6C=3E 6D=42 6E=4D 6F=5D 
70=78 71=00 72=00 73=32 74=3C 75=41 76=4B 77=4B 
78=64 79=64 7A=03 7B=02 7C=02 7D=02 7E=03 7F=05 
80=00 81=00 82=32 83=3C 84=46 85=52 86=5A 87=5D 
88=64 89=00 8A=2D 8B=32 8C=41 8D=48 8E=50 8F=55 
90=64 91=00 92=03 93=05 94=05 95=06 96=03 97=03 
98=06 99=19 9A=73 9B=02 9C=00 9D=66 9E=00 9F=00 
A0=31 A1=35 A2=48 A3=4B A4=45 A5=4D A6=53 A7=31 
A8=2E A9=31 AA=30 AB=34 AC=31 AD=30 AE=32 AF=34 
B0=32 B1=30 B2=32 B3=32 B4=31 B5=30 B6=3A B7=35 
B8=38 B9=3A BA=31 BB=39 BC=49 BD=0C BE=00 BF=08 
C0=00 C1=07 C2=23 C3=0F C4=00 C5=9E C6=40 C7=00 
C8=00 C9=84 CA=00 CB=00 CC=00 CD=00 CE=14 CF=00 
D0=00 D1=00 D2=00 D3=00 D4=70 D5=00 D6=00 D7=00 
D8=2B D9=50 DA=33 DB=80 DC=00 DD=17 DE=0A DF=1F 
E0=E2 E1=02 E2=00 E3=00 E4=10 E5=00 E6=00 E7=00 
E8=00 E9=00 EA=2E EB=30 EC=00 ED=C0 EE=00 EF=BC 
F0=00 F1=00 F2=C2 F3=80 F4=0D F5=00 F6=05 F7=0A 
F8=0B F9=0D FA=00 FB=00 FC=00 FD=00 FE=00 FF=00

**Comment by CosmicRaptor** [comment]
Okay, here's what I tested so far.

Backlight off: 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/b4c0ae7f-a234-422e-893d-53ec1a05e30b)


Backlight max:
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/1bb12f10-6954-4cbe-a1f2-1d6d1f852053)

Backlight medium:
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/7a6974d4-dd25-4dd1-8bb1-38204e0ce04b)

Backlight low:
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/1af88c43-8574-4959-a78b-5bacd8269649)


Based on this, this bit seems to be the one handling backlight. (F003? Am I saying it right?) 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/d37ea8d6-eff5-4be8-842f-3a3a6cd506e9)

Moving on, here's more findings

"AI" mode: 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/3d0eaa01-c8ff-4ec7-a12a-f489f987d4ce)

Performance mode: (fan speed auto, cooler boost off)
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/13598937-f6ab-4a2d-acf8-a56994472bb3)

Balanced mode: 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/f4d0c643-884c-4ad2-bcee-250243b6533b)

Silent mode: 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/e5ecf9e1-1760-4455-81ec-1abd6e042df6)

Super battery: 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/ed2489d0-a6f3-4239-a211-92c5b163507d)

**Comment by CosmicRaptor** [comment]
Best for battery(60% limit) mode: 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/00352949-ecaf-4678-b327-5080a65168df)

Balanced battery mode(80% limit): 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/4ed299fe-b2b2-4318-b61a-77e23193e1ea)

Best for mobility(100% charge limit): 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/8e245837-eba2-471f-9c46-2581eb393ee9)


Above tests were conducted while plugged in.

**Comment by CosmicRaptor** [comment]
Also, a few of the EC addresses keep changing on every refresh even if I am not doing any changes. Is that because of the RTC or something like that?

**Comment by CosmicRaptor** [comment]
This byte handles mute/unmute 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/7303d00e-aa25-4d41-9470-e58c05c2d1cc)


This one is for toggling the mic 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/d1b49e9d-5a65-41d8-ad8d-1c506adb73ec)

This one toggles the webcam 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/d822e9ff-e95e-4c0e-912b-dcc5d0838e06)


This one toggles the Fn+Esc LED 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/caf57b86-da71-46f4-be12-130f674cc00c)

**Comment by glpnk** [comment]
@CosmicRaptor 

> Also, a few of the EC addresses keep changing on every refresh even if I am not doing any changes. Is that because of the RTC or something like that?

Yeah you kinda right, but someone is temperature, cooler RPM, other, I think, may be related to some voltage, power or other internal logic, something may be related to RTC. Earlier in `dmesg` I have some messages related to EC with RTC phrase like 'method not found'

**Comment by CosmicRaptor** [comment]
> @CosmicRaptor
> 
> > Also, a few of the EC addresses keep changing on every refresh even if I am not doing any changes. Is that because of the RTC or something like that?
> 
> Yeah you kinda right, but someone is temperature, cooler RPM, other, I think, may be related to some voltage, power or other internal logic, something may be related to RTC. Earlier in `dmesg` I have some messages related to EC with RTC phrase like 'method not found'

Oh yeah a few of those absolutely are the cpu frequency, temperature and fan speed. I'm just not sure which. I'm also not sure if the RTC is in the EC or not.

**Comment by glpnk** [comment]
About RTC - it does not matter, read wiki to see which values are required and supported.

**Comment by CosmicRaptor** [comment]
How would I figure out the addresses for the battery modes? Lots of addresses change on switching the modes and I am not sure which one does what.

This is basically everything that I found out so far.
```webcam LED: 0x2e
mic LED: 0x2b
speaker mute LED: 0x2c
Fn + Esc LED: 0x2b (not sure!)

keyboard backlight: 0x3f (80=off, 81= min brightness, 82= mid brightness, 83= max brightness)

**Comment by glpnk** [comment]
B7M is 17 inch or amd 7 gen laptop? I think you can check values from B5M (unfinished) or A5M [pr#66](https://github.com/BeardOverflow/msi-ec/pull/66/files) or [C5M](https://github.com/BeardOverflow/msi-ec/pull/37/files).

You can document unnecessary values if you want or just check all addresses from diff's above or wiki.

**Comment by CosmicRaptor** [comment]
> B7M is 17 inch or amd 7 gen laptop? I think you can check values from B5M (unfinished) or A5M [pr#66](https://github.com/BeardOverflow/msi-ec/pull/66/files) or [C5M](https://github.com/BeardOverflow/msi-ec/pull/37/files).
> 
> You can document unnecessary values if you want or just check all addresses from diff's above or wiki.

It is 15 inch ryzen 7000 laptop. Mine has a ryzen 5 7530U
I will check those PRs and compare, thank you.

**Comment by CosmicRaptor** [comment]
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/c8b914e9-f0d0-4ba3-9e3a-14505fc897a0)
I think only these parameters change on changing the shift modes. This seems to match with the C5M so far from what I can tell.

**Comment by glpnk** [comment]
`f2` - shift (like C5M)
`f4` - fan mode - check is extended/manual fan curve is available (value may be `8d` or any `8_`)

`f6-f9` - I think are unnecessary

**Comment by CosmicRaptor** [comment]
> `f2` - shift (like C5M) `f4` - fan mode - check is extended/manual fan curve is available (value may be `8d` or any `8_`)
> 
> `f6-f9` - I think are unnecessary
> 
> DONT Change unknown values because sometimes your laptop may die

There is a 6 point manual fan curve supported under the performance mode. I however do not use it, the stock feels good enough. Is it necessary to test that?

**Comment by CosmicRaptor** [comment]
In charge control, there are a couple of offsets mentioned. What do those do? I have not found those for mine yet.
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/b3faad8a-c698-4aa4-8cbb-7da92f09df6d)

I have also not found the addresses for the range_min and range_max

**Comment by glpnk** [comment]
> There is a 6 point manual fan curve supported under the performance mode

Only `f4` value, curve addresses seem the same in all models

> In charge control, there are a couple of offsets mentioned. What do those do? I have not found those for mine yet.

offset seems default too, I think it was there since first releases, if values in range 0-100 in decimal, you not need to change nothing 

check that `0xEF` address set to next values through battery safe modes (ignore AI mode if present):  0x3C (60%), 0x50 (80%), 0x64 (100%)

**Comment by CosmicRaptor** [comment]
> check that `0xEF` address set to next values through battery safe modes (ignore AI mode if present): 0x3C (60%), 0x50 (80%), 0x64 (100%)


the values do not match. 
![image](https://github.com/BeardOverflow/msi-ec/assets/60008842/7d4e2ab4-e85e-4449-823b-a0138174ebc5)

**Comment by glpnk** [comment]
> 100% limit = E4

0xE4=228, 100=0x64, 0xE4-0x64= `0x80` or 128 in decimal

So value has offset, for my model (C5M) value for 100% charge is also `E4`.

If you copied this section from my config - they match

**Comment by CosmicRaptor** [comment]
> > 100% limit = E4
> 
> 0xE4=228, 100=0x64, 0xE4-0x64= `0x80` or 128 in decimal
> 
> So value has offset, for my model (C5M) value for 100% charge is also `E4`.
> 
> If you copied this section from my config - they match

Sorry I'm new to this, are you saying that this is an exact match with the C5M?

**Comment by CosmicRaptor** [comment]
> Battery offsets and range values are the same for all currently supported models.
> 
> Address `0xEF` is similar for some models. And it similar to the B5M and C5M that I referenced [before](https://github.com/BeardOverflow/msi-ec/issues/89#issuecomment-1806854128)
> 
> I think (but not prove) that addresses is nearly identical for all models in each device class (like "business" or "gaming") within the some production date range, so you can use similar models for reference and prove it similarity after research.

You are correct. Most of the values are matching, as I've found here. I think my work is done then. What else am I supposed to do? I'm not a C programmer so I cannot file a PR.

**Comment by glpnk** [comment]
> I think my work is done then.

Thank you. Please share which config to use as reference and which addresses are different, unknown and untested (if they exists). You can share your notes as is or as edited config.

Do you want to test this config on linux?

**Comment by CosmicRaptor** [comment]
> > I think my work is done then.
> 
> Thank you. Please share which config to use as reference and which addresses are different, unknown and untested (if they exists). You can share your notes as is or as edited config.
> 
> Do you want to test this config on linux?

Okay, I'm using the C5M as reference. Here's my entire findings 
[msi-ec-b7m.txt](https://github.com/BeardOverflow/msi-ec/files/13351814/msi-ec-b7m.txt)

 I would like to try this on linux, to make sure everything works.

**Comment by glpnk** [comment]
@CosmicRaptor, sorry for late reply, but I've seen your previous reply, before you wrote about checking

[Link to fork](https://github.com/glpnk/msi-ec/tree/15HKEMS1)


Download with

```bash
git clone -b 15HKEMS1 https://github.com/glpnk/msi-ec.git
```

Make and load

```bash
make
sudo make load
```

Or install with DKMS

```bash
sudo make dkms-install
```

**Comment by CosmicRaptor** [comment]
Thank you for creating the PR! I just tested it out on fedora.
All fan modes work. The mic mute LED and speaker mute LED are not working. Need to investigate that. Battery charge thresholds are working. Cooler boost works too.

Also, my brightness keeps changing randomly as soon as i use a function key. Any fix to this?

**Comment by glpnk** [comment]
About mute LEDs - it can be broken triggers t volume levels, on POP OS only `mic mute` works, but I can lit `audio mute` LED manually.

Copy each command separately.

```bash
# off audio mute LED
echo 0 | sudo tee /sys/class/leds/platform::mute/brightness

# on audio mute LED
echo 1 | sudo tee /sys/class/leds/platform::mute/brightness


# off mic mute LED
echo 0 | sudo tee /sys/class/leds/platform::micmute/brightness

# on mic mute LED
echo 1 | sudo tee /sys/class/leds/platform::micmute/brightness
```

About brightness changing - it's a bug in graphics card or other driver - you need to blacklist some driver.
For now - don't use keyboard for brightness control

I think this helped me with brightness issue https://discussion.fedoraproject.org/t/79613/8
But I think that I changed some other file, because this is overwritten after updates

**Comment by CosmicRaptor** [comment]
Yes, those commands work. So this is a weird bug I guess.

The fix you gave me is for xorg, I am unsure if that will work on GNOME Wayland. Will have to try. I think I'm done then, I'll finally install linux on this laptop. Thank you for your time!

**Comment by glpnk** [comment]
If you find fix for Wayland please share it.

Checklist:

| Config | Status |
|:---|:--:|
| Charge control | ✅ |
| Webcam block | ❓ |
| FN-Win swap | ❓ |
| Cooler boost | ✅ |
| Shifts | ❓✅ |
| Super battery | ❌ |
| Fan mode | ✅ |
| CPU temp/speed | ❓ |
| GPU | ❌ |
| mute LEDs | ✅ |
| Keyboard backlight | ✅ |

Please check question marked modes from checklist (I'll reply how to test this later)

**Comment by CosmicRaptor** [comment]
Checklist:
Config 	Status
Charge control 	✅
Webcam block 	✅
 FN-Win swap 	✅
Cooler boost 	✅
Shifts 	✅
Super battery 	✅
Fan mode 	✅
CPU temp/speed 	✅
GPU 	❌ this laptop has iGPU so this is irrelevant
mute LEDs 	✅
Keyboard backlight 	✅

**Comment by glpnk** [comment]
Awesome

**Comment by CosmicRaptor** [comment]
I have a really weird issue, not sure if this is related to my hardware or the driver.

Whenever my fans spin up from 0%, there's a click sound. It's almost like the sound of a CD drive getting ejected. It's not very loud but noticeable. Do you or anyone else have this issue as well?

**Comment by glpnk** [comment]
I think I have same sound, but it quite silent and at the same time annoying. Some people change idle fan curve value to lowest RPM possible, but I think is too fast. But it "fixes" continuous start-stopping.

On Linux CPU on idle could be colder, so it runs on passive cooling.

**Comment by CosmicRaptor** [comment]
Tiny issue ive been having, on every boot the shift mode is reset to "comfort"
is this a known issue or I have the incorrect EC values?

**Comment by glpnk** [comment]
> @CosmicRaptor: Also, my brightness keeps changing randomly as soon as i use a function key. Any fix to this?
> @glpnk: I think this helped me with brightness issue https://discussion.fedoraproject.org/t/79613/8
> @CosmicRaptor: The fix you gave me is for xorg, I am unsure if that will work on GNOME Wayland. Will have to try. I think I'm done then, I'll finally install linux on this laptop. Thank you for your time!

Hi, @CosmicRaptor, do you found how to fix brightness issue on Wayland? I think the simplest way is somehow disable event source. Maybe you know fix?

**Comment by CosmicRaptor** [comment]
> > @CosmicRaptor: Also, my brightness keeps changing randomly as soon as i use a function key. Any fix to this?
> > @glpnk: I think this helped me with brightness issue https://discussion.fedoraproject.org/t/79613/8
> > @CosmicRaptor: The fix you gave me is for xorg, I am unsure if that will work on GNOME Wayland. Will have to try. I think I'm done then, I'll finally install linux on this laptop. Thank you for your time!
> 
> Hi, @CosmicRaptor, do you found how to fix brightness issue on Wayland? I think the simplest way is somehow disable event source. Maybe you know fix?
> 
> UPD: https://askubuntu.com/a/1487963 but on different Wayland version this prop could have different name
> 
> ```ini
> [Video Bus Spooky Ghost]
> MatchName=*Video Bus*
> AttrEventCodeDisable=EV_KEY:0xE0;EV_KEY:0xE1;
> ```

You are correct, the same fix works.

**Comment by teackot** [comment]
Closing, since #91 was merged

@CosmicRaptor thank you for providing the info! You can now switch to the main repo, feel free to open a new issue if you find any problems or have any suggestions

**Comment by CosmicRaptor** [comment]
Sure thing! Thanks for merging
