### ISSUE TITLE
Assign `msi-ec` group to msi-ec files

### ISSUE THREAD

**Issue by lmaxyz** [BeardOverflow/msi-ec#94]
I don't know about drivers much, so question might be nooby.
Is there any option to assign group, for example `msi-ec` , for all files inside `/sys/devices/platform/msi-ec/` directory?

I want it because I wrote some little GUI app, and I have to run it with root privileges all the time to allow app to interact with device's files. It's not very comfortable because at least root's UI settings are different from user's ones so app becomes ugly and it also requires terminal to be constantly opened.

**Comment by glpnk** [comment]
For this purposes you can write service which will interact with `msi-ec` like it made in [MControlCenter](https://github.com/dmitry-s93/MControlCenter) or use it without writing new app

**Comment by lmaxyz** [comment]
Sounds good. Thanks!
